// Mock data for development when backend is unavailable
// All data here is marked as "backend-dependent"

import type {
  Question,
  QuestionCategory,
  QuestionType,
  Exam,
  ExamSection,
  Attempt,
  GradingSession,
  ExamResult,
  ProctorSession,
  IncidentCase,
  AuditLog,
} from "@/lib/types";
import {
  DifficultyLevel,
  AttemptStatus,
  ExamType,
  GradingStatus,
  ProctorMode,
  ProctorDecisionStatus,
  IncidentSource,
  IncidentSeverity,
  IncidentStatus,
} from "@/lib/types";

// Question Categories
export const mockQuestionCategories: QuestionCategory[] = [
  {
    id: 1,
    nameEn: "Mathematics",
    nameAr: "الرياضيات",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 2,
    nameEn: "Science",
    nameAr: "العلوم",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 3,
    nameEn: "English",
    nameAr: "اللغة الإنجليزية",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 4,
    nameEn: "History",
    nameAr: "التاريخ",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 5,
    nameEn: "Computer Science",
    nameAr: "علوم الحاسب",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
];

// Question Types
export const mockQuestionTypes: QuestionType[] = [
  {
    id: 1,
    nameEn: "MCQ Single",
    nameAr: "اختيار من متعدد (إجابة واحدة)",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 2,
    nameEn: "MCQ Multi",
    nameAr: "اختيار من متعدد (إجابات متعددة)",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 3,
    nameEn: "True/False",
    nameAr: "صح/خطأ",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
  {
    id: 4,
    nameEn: "Subjective",
    nameAr: "سؤال مقالي",
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
  },
];

// Questions
export const mockQuestions: Question[] = [
  {
    id: 1,
    bodyEn: "What is the capital of France?",
    bodyAr: "What is the capital of France?",
    body: "What is the capital of France?",
    questionTypeId: 1,
    questionTypeNameEn: "MCQ Single",
    questionTypeNameAr: "MCQ Single",
    questionTypeName: "MCQ Single",
    questionCategoryId: 4,
    questionCategoryNameEn: "History",
    questionCategoryNameAr: "History",
    questionCategoryName: "History",
    subjectId: 4,
    subjectNameEn: "History",
    subjectNameAr: "History",
    topicId: null,
    topicNameEn: null,
    topicNameAr: null,
    points: 2,
    difficultyLevel: DifficultyLevel.Easy,
    difficultyLevelName: "Easy",
    isActive: true,
    isCalculatorAllowed: false,
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
    options: [
      {
        id: 1,
        questionId: 1,
        textEn: "Paris",
        textAr: "Paris",
        text: "Paris",
        isCorrect: true,
        order: 0,
        attachmentPath: null,
        createdDate: "2024-01-01T00:00:00Z",
      },
      {
        id: 2,
        questionId: 1,
        textEn: "London",
        textAr: "London",
        text: "London",
        isCorrect: false,
        order: 1,
        attachmentPath: null,
        createdDate: "2024-01-01T00:00:00Z",
      },
      {
        id: 3,
        questionId: 1,
        textEn: "Berlin",
        textAr: "Berlin",
        text: "Berlin",
        isCorrect: false,
        order: 2,
        attachmentPath: null,
        createdDate: "2024-01-01T00:00:00Z",
      },
      {
        id: 4,
        questionId: 1,
        textEn: "Madrid",
        textAr: "Madrid",
        text: "Madrid",
        isCorrect: false,
        order: 3,
        attachmentPath: null,
        createdDate: "2024-01-01T00:00:00Z",
      },
    ],
    attachments: [],
    optionsCount: 4,
    attachmentsCount: 0,
  },
  {
    id: 2,
    bodyEn: "Solve: 2x + 5 = 15. What is x?",
    bodyAr: "Solve: 2x + 5 = 15. What is x?",
    body: "Solve: 2x + 5 = 15. What is x?",
    questionTypeId: 1,
    questionTypeNameEn: "MCQ Single",
    questionTypeNameAr: "MCQ Single",
    questionTypeName: "MCQ Single",
    questionCategoryId: 1,
    questionCategoryNameEn: "Mathematics",
    questionCategoryNameAr: "Mathematics",
    questionCategoryName: "Mathematics",
    subjectId: 1,
    subjectNameEn: "Mathematics",
    subjectNameAr: "Mathematics",
    topicId: null,
    topicNameEn: null,
    topicNameAr: null,
    points: 3,
    difficultyLevel: DifficultyLevel.Medium,
    difficultyLevelName: "Medium",
    isActive: true,
    isCalculatorAllowed: false,
    createdDate: "2024-01-02T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
    options: [
      {
        id: 5,
        questionId: 2,
        textEn: "5",
        textAr: "5",
        text: "5",
        isCorrect: true,
        order: 0,
        attachmentPath: null,
        createdDate: "2024-01-02T00:00:00Z",
      },
      {
        id: 6,
        questionId: 2,
        textEn: "10",
        textAr: "10",
        text: "10",
        isCorrect: false,
        order: 1,
        attachmentPath: null,
        createdDate: "2024-01-02T00:00:00Z",
      },
      {
        id: 7,
        questionId: 2,
        textEn: "7.5",
        textAr: "7.5",
        text: "7.5",
        isCorrect: false,
        order: 2,
        attachmentPath: null,
        createdDate: "2024-01-02T00:00:00Z",
      },
      {
        id: 8,
        questionId: 2,
        textEn: "3",
        textAr: "3",
        text: "3",
        isCorrect: false,
        order: 3,
        attachmentPath: null,
        createdDate: "2024-01-02T00:00:00Z",
      },
    ],
    attachments: [],
    optionsCount: 4,
    attachmentsCount: 0,
  },
  {
    id: 3,
    bodyEn: "The Earth revolves around the Sun.",
    bodyAr: "The Earth revolves around the Sun.",
    body: "The Earth revolves around the Sun.",
    questionTypeId: 3,
    questionTypeNameEn: "True/False",
    questionTypeNameAr: "True/False",
    questionTypeName: "True/False",
    questionCategoryId: 2,
    questionCategoryNameEn: "Science",
    questionCategoryNameAr: "Science",
    questionCategoryName: "Science",
    subjectId: 2,
    subjectNameEn: "Science",
    subjectNameAr: "Science",
    topicId: null,
    topicNameEn: null,
    topicNameAr: null,
    points: 1,
    difficultyLevel: DifficultyLevel.Easy,
    difficultyLevelName: "Easy",
    isActive: true,
    isCalculatorAllowed: false,
    createdDate: "2024-01-03T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
    options: [
      {
        id: 9,
        questionId: 3,
        textEn: "True",
        textAr: "True",
        text: "True",
        isCorrect: true,
        order: 0,
        attachmentPath: null,
        createdDate: "2024-01-03T00:00:00Z",
      },
      {
        id: 10,
        questionId: 3,
        textEn: "False",
        textAr: "False",
        text: "False",
        isCorrect: false,
        order: 1,
        attachmentPath: null,
        createdDate: "2024-01-03T00:00:00Z",
      },
    ],
    attachments: [],
    optionsCount: 2,
    attachmentsCount: 0,
  },
  {
    id: 4,
    bodyEn:
      "Explain the concept of Object-Oriented Programming and its four main principles.",
    bodyAr:
      "Explain the concept of Object-Oriented Programming and its four main principles.",
    body: "Explain the concept of Object-Oriented Programming and its four main principles.",
    questionTypeId: 5,
    questionTypeNameEn: "Essay",
    questionTypeNameAr: "Essay",
    questionTypeName: "Essay",
    questionCategoryId: 5,
    questionCategoryNameEn: "Computer Science",
    questionCategoryNameAr: "Computer Science",
    questionCategoryName: "Computer Science",
    subjectId: 5,
    subjectNameEn: "Computer Science",
    subjectNameAr: "Computer Science",
    topicId: null,
    topicNameEn: null,
    topicNameAr: null,
    points: 10,
    difficultyLevel: DifficultyLevel.Hard,
    difficultyLevelName: "Hard",
    isActive: true,
    isCalculatorAllowed: false,
    createdDate: "2024-01-04T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
    options: [],
    attachments: [],
    optionsCount: 0,
    attachmentsCount: 0,
  },
  {
    id: 5,
    bodyEn: "What is the chemical symbol for water?",
    bodyAr: "What is the chemical symbol for water?",
    body: "What is the chemical symbol for water?",
    questionTypeId: 1,
    questionTypeNameEn: "MCQ Single",
    questionTypeNameAr: "MCQ Single",
    questionTypeName: "MCQ Single",
    questionCategoryId: 2,
    questionCategoryNameEn: "Science",
    questionCategoryNameAr: "Science",
    questionCategoryName: "Science",
    subjectId: 2,
    subjectNameEn: "Science",
    subjectNameAr: "Science",
    topicId: null,
    topicNameEn: null,
    topicNameAr: null,
    points: 2,
    difficultyLevel: DifficultyLevel.Easy,
    difficultyLevelName: "Easy",
    isActive: true,
    isCalculatorAllowed: false,
    createdDate: "2024-01-05T00:00:00Z",
    updatedDate: null,
    isDeleted: false,
    options: [
      {
        id: 11,
        questionId: 5,
        textEn: "H2O",
        textAr: "H2O",
        text: "H2O",
        isCorrect: true,
        order: 0,
        attachmentPath: null,
        createdDate: "2024-01-05T00:00:00Z",
      },
      {
        id: 12,
        questionId: 5,
        textEn: "CO2",
        textAr: "CO2",
        text: "CO2",
        isCorrect: false,
        order: 1,
        attachmentPath: null,
        createdDate: "2024-01-05T00:00:00Z",
      },
      {
        id: 13,
        questionId: 5,
        textEn: "NaCl",
        textAr: "NaCl",
        text: "NaCl",
        isCorrect: false,
        order: 2,
        attachmentPath: null,
        createdDate: "2024-01-05T00:00:00Z",
      },
      {
        id: 14,
        questionId: 5,
        textEn: "O2",
        textAr: "O2",
        text: "O2",
        isCorrect: false,
        order: 3,
        attachmentPath: null,
        createdDate: "2024-01-05T00:00:00Z",
      },
    ],
    attachments: [],
    optionsCount: 4,
    attachmentsCount: 0,
  },
];

// Exam Sections
export const mockSections: ExamSection[] = [
  {
    id: 1,
    examId: 1,
    titleEn: "Section 1: Basic Knowledge",
    titleAr: "القسم الأول: المعرفة الأساسية",
    descriptionEn: "Answer all questions in this section",
    descriptionAr: "أجب على جميع الأسئلة في هذا القسم",
    order: 0,
    durationMinutes: 30,
    totalPointsOverride: null,
    createdDate: "2024-01-01T00:00:00Z",
    topicsCount: 0,
    questionsCount: 10,
    totalPoints: 20,
    topics: [],
    questions: [],
  },
  {
    id: 2,
    examId: 1,
    titleEn: "Section 2: Advanced Topics",
    titleAr: "القسم الثاني: المواضيع المتقدمة",
    descriptionEn: "Choose 3 questions from this section",
    descriptionAr: "اختر 3 أسئلة من هذا القسم",
    order: 1,
    durationMinutes: 45,
    totalPointsOverride: null,
    createdDate: "2024-01-01T00:00:00Z",
    topicsCount: 0,
    questionsCount: 5,
    totalPoints: 30,
    topics: [],
    questions: [],
  },
];

// Exam Schedules
interface MockExamSchedule {
  id: number;
  examId: number;
  startAt: string;
  endAt: string;
  location: string;
  capacity: number;
  registeredCount: number;
  isActive: boolean;
}

export const mockSchedules: MockExamSchedule[] = [
  {
    id: 1,
    examId: 1,
    startAt: "2024-02-01T09:00:00Z",
    endAt: "2024-02-01T12:00:00Z",
    location: "Main Hall - Room A",
    capacity: 50,
    registeredCount: 35,
    isActive: true,
  },
  {
    id: 2,
    examId: 1,
    startAt: "2024-02-02T14:00:00Z",
    endAt: "2024-02-02T17:00:00Z",
    location: "Main Hall - Room B",
    capacity: 30,
    registeredCount: 28,
    isActive: true,
  },
  {
    id: 3,
    examId: 2,
    startAt: "2024-02-15T10:00:00Z",
    endAt: "2024-02-15T11:30:00Z",
    location: "Science Lab",
    capacity: 25,
    registeredCount: 20,
    isActive: true,
  },
];

// Exams
const mockExamPolicyDefaults = {
  departmentId: 0,
  showResults: false,
  allowReview: false,
  showCorrectAnswers: false,
  requireProctoring: false,
  requireIdVerification: false,
  requireWebcam: false,
  enableScreenMonitoring: false,
  screenMonitoringMode: 0,
  screenShareGracePeriod: 20,
  preventCopyPaste: false,
  preventScreenCapture: false,
  requireFullscreen: false,
  browserLockdown: false,
  maxViolationWarnings: 3,
} satisfies Pick<
  Exam,
  | "departmentId"
  | "showResults"
  | "allowReview"
  | "showCorrectAnswers"
  | "requireProctoring"
  | "requireIdVerification"
  | "requireWebcam"
  | "enableScreenMonitoring"
  | "screenMonitoringMode"
  | "screenShareGracePeriod"
  | "preventCopyPaste"
  | "preventScreenCapture"
  | "requireFullscreen"
  | "browserLockdown"
  | "maxViolationWarnings"
>;

export const mockExams: Exam[] = [
  {
    ...mockExamPolicyDefaults,
    id: 1,
    examType: ExamType.Fixed,
    title: "Final Mathematics Exam",
    code: "MATH-001",
    status: "Published",
    titleEn: "Final Mathematics Exam",
    titleAr: "الاختبار النهائي للرياضيات",
    descriptionEn: "Comprehensive mathematics examination covering all topics",
    descriptionAr: "اختبار رياضيات شامل يغطي جميع المواضيع",
    startAt: "2024-02-01T09:00:00Z",
    endAt: "2024-02-01T12:00:00Z",
    durationMinutes: 120,
    maxAttempts: 2,
    shuffleQuestions: true,
    shuffleOptions: true,
    passScore: 60,
    passingScore: 60,
    isPublished: true,
    isActive: true,
    createdDate: "2024-01-01T00:00:00Z",
    updatedDate: null,
    sectionsCount: 2,
    questionsCount: 15,
    totalPoints: 50,
    sections: mockSections,
    instructions: [
      {
        id: 1,
        examId: 1,
        contentEn: "Read all questions carefully before answering",
        contentAr: "اقرأ جميع الأسئلة بعناية قبل الإجابة",
        order: 0,
        createdDate: "2024-01-01T00:00:00Z",
      },
      {
        id: 2,
        examId: 1,
        contentEn: "No calculators allowed",
        contentAr: "لا يُسمح باستخدام الآلات الحاسبة",
        order: 1,
        createdDate: "2024-01-01T00:00:00Z",
      },
    ],
    accessPolicy: {
      id: 1,
      examId: 1,
      isPublic: false,
      accessCode: "MATH2024",
      restrictToAssignedCandidates: true,
      isWalkIn: false,
      createdDate: "2024-01-01T00:00:00Z",
      updatedDate: null,
    },
  },
  {
    ...mockExamPolicyDefaults,
    id: 2,
    examType: ExamType.Fixed,
    title: "Science Mid-Term Exam",
    code: "SCI-002",
    status: "Published",
    titleEn: "Science Mid-Term Exam",
    titleAr: "اختبار منتصف الفصل للعلوم",
    descriptionEn: "Mid-term examination covering chapters 1-5",
    descriptionAr: "اختبار منتصف الفصل يغطي الفصول 1-5",
    startAt: "2024-02-15T10:00:00Z",
    endAt: "2024-02-15T11:30:00Z",
    durationMinutes: 90,
    maxAttempts: 1,
    shuffleQuestions: true,
    shuffleOptions: false,
    passScore: 50,
    passingScore: 50,
    isPublished: true,
    isActive: true,
    createdDate: "2024-01-15T00:00:00Z",
    updatedDate: null,
    sectionsCount: 1,
    questionsCount: 25,
    totalPoints: 100,
    sections: [],
    instructions: [],
    accessPolicy: {
      id: 2,
      examId: 2,
      isPublic: true,
      accessCode: null,
      restrictToAssignedCandidates: false,
      isWalkIn: false,
      createdDate: "2024-01-15T00:00:00Z",
      updatedDate: null,
    },
  },
  {
    ...mockExamPolicyDefaults,
    id: 3,
    examType: ExamType.Flex,
    title: "Computer Science Quiz",
    code: "CS-003",
    status: "Draft",
    titleEn: "Computer Science Quiz",
    titleAr: "اختبار قصير في علوم الحاسب",
    descriptionEn: "Quick quiz on programming fundamentals",
    descriptionAr: "اختبار قصير في أساسيات البرمجة",
    startAt: null,
    endAt: null,
    durationMinutes: 30,
    maxAttempts: 3,
    shuffleQuestions: false,
    shuffleOptions: true,
    passScore: 70,
    passingScore: 70,
    isPublished: false,
    isActive: true,
    createdDate: "2024-01-20T00:00:00Z",
    updatedDate: null,
    sectionsCount: 1,
    questionsCount: 10,
    totalPoints: 20,
    sections: [],
    instructions: [],
    accessPolicy: null,
  },
  {
    ...mockExamPolicyDefaults,
    id: 4,
    examType: ExamType.Fixed,
    title: "English Proficiency Test",
    code: "ENG-004",
    status: "Archived",
    titleEn: "English Proficiency Test",
    titleAr: "اختبار الكفاءة في اللغة الإنجليزية",
    descriptionEn: "Comprehensive English language assessment",
    descriptionAr: "تقييم شامل للغة الإنجليزية",
    startAt: "2024-01-10T08:00:00Z",
    endAt: "2024-01-10T10:00:00Z",
    durationMinutes: 120,
    maxAttempts: 1,
    shuffleQuestions: true,
    shuffleOptions: true,
    passScore: 65,
    passingScore: 65,
    isPublished: true,
    isActive: false,
    createdDate: "2024-01-05T00:00:00Z",
    updatedDate: "2024-01-20T00:00:00Z",
    sectionsCount: 3,
    questionsCount: 40,
    totalPoints: 100,
    sections: [],
    instructions: [],
    accessPolicy: null,
  },
];

// Attempts
export const mockAttempts: Attempt[] = [
  {
    id: 1,
    examId: 1,
    examTitleEn: "Final Mathematics Exam",
    examTitleAr: "الاختبار النهائي للرياضيات",
    candidateId: "3",
    candidateName: "Ahmed Hassan",
    startedAt: "2024-02-01T09:05:00Z",
    submittedAt: "2024-02-01T10:45:00Z",
    expiresAt: "2024-02-01T11:05:00Z",
    status: AttemptStatus.Submitted,
    statusName: "Submitted",
    attemptNumber: 1,
    totalQuestions: 15,
    answeredQuestions: 15,
    score: 78,
    isPassed: true,
  },
  {
    id: 2,
    examId: 1,
    examTitleEn: "Final Mathematics Exam",
    examTitleAr: "الاختبار النهائي للرياضيات",
    candidateId: "4",
    candidateName: "Sara Ali",
    startedAt: "2024-02-01T09:10:00Z",
    submittedAt: null,
    expiresAt: "2024-02-01T11:10:00Z",
    status: AttemptStatus.InProgress,
    statusName: "In Progress",
    attemptNumber: 1,
    totalQuestions: 15,
    answeredQuestions: 8,
  },
  {
    id: 3,
    examId: 2,
    examTitleEn: "Science Mid-Term Exam",
    examTitleAr: "اختبار منتصف الفصل للعلوم",
    candidateId: "3",
    candidateName: "Ahmed Hassan",
    startedAt: "2024-02-15T10:00:00Z",
    submittedAt: "2024-02-15T11:15:00Z",
    expiresAt: "2024-02-15T11:30:00Z",
    status: AttemptStatus.Submitted,
    statusName: "Submitted",
    attemptNumber: 1,
    totalQuestions: 25,
    answeredQuestions: 23,
    score: 65,
    isPassed: true,
  },
];

// Grading Sessions
export const mockGradingSessions: GradingSession[] = [
  {
    id: 1,
    attemptId: 1,
    examId: 1,
    examTitleEn: "Final Mathematics Exam",
    candidateId: "3",
    candidateName: "Ahmed Hassan",
    status: GradingStatus.Completed,
    statusName: "Completed",
    totalScore: 78,
    maxPossibleScore: 100,
    passScore: 60,
    isPassed: true,
    totalQuestions: 15,
    gradedQuestions: 15,
    manualGradingRequired: 0,
    answers: [],
  },
  {
    id: 2,
    attemptId: 3,
    examId: 2,
    examTitleEn: "Science Mid-Term Exam",
    candidateId: "3",
    candidateName: "Ahmed Hassan",
    status: GradingStatus.RequiresManualGrading,
    statusName: "Requires Manual Grading",
    totalScore: null,
    maxPossibleScore: 100,
    passScore: 50,
    isPassed: null,
    totalQuestions: 25,
    gradedQuestions: 22,
    manualGradingRequired: 3,
    answers: [],
  },
];

// Exam Results
export const mockExamResults: ExamResult[] = [
  {
    id: 1,
    attemptId: 1,
    examId: 1,
    examTitleEn: "Final Mathematics Exam",
    examTitleAr: "الاختبار النهائي للرياضيات",
    candidateId: "3",
    candidateName: "Ahmed Hassan",
    totalScore: 78,
    maxPossibleScore: 100,
    passScore: 60,
    isPassed: true,
    isPublished: true,
    finalizedAt: "2024-02-01T11:00:00Z",
    publishedAt: "2024-02-02T09:00:00Z",
  },
];

// Proctor Sessions
export const mockProctorSessions: ProctorSession[] = [
  {
    id: 1,
    attemptId: 1,
    examId: 1,
    candidateId: "3",
    candidateName: "Ahmed Hassan",
    mode: ProctorMode.Soft,
    modeName: "Soft",
    startedAt: "2024-02-01T09:05:00Z",
    endedAt: "2024-02-01T10:45:00Z",
    status: 2,
    statusName: "Completed",
    riskScore: 15.5,
    totalEvents: 45,
    totalViolations: 3,
    deviceFingerprint: "abc123xyz",
    browserName: "Chrome",
    operatingSystem: "Windows 11",
    decisionStatus: ProctorDecisionStatus.Cleared,
    decisionStatusName: "Cleared",
  },
  {
    id: 2,
    attemptId: 2,
    examId: 1,
    candidateId: "4",
    candidateName: "Sara Ali",
    mode: ProctorMode.Soft,
    modeName: "Soft",
    startedAt: "2024-02-01T09:10:00Z",
    endedAt: null,
    status: 1,
    statusName: "Active",
    riskScore: 45.0,
    totalEvents: 120,
    totalViolations: 12,
    deviceFingerprint: "def456abc",
    browserName: "Firefox",
    operatingSystem: "macOS",
    decisionStatus: ProctorDecisionStatus.RequiresReview,
    decisionStatusName: "Requires Review",
  },
];

// Incident Cases
export const mockIncidentCases: IncidentCase[] = [
  {
    id: 1,
    attemptId: 2,
    proctorSessionId: 2,
    examId: 1,
    examTitleEn: "Final Mathematics Exam",
    candidateId: "4",
    candidateName: "Sara Ali",
    source: IncidentSource.Proctor,
    sourceName: "Proctor",
    severity: IncidentSeverity.High,
    severityName: "High",
    status: IncidentStatus.Open,
    statusName: "Open",
    outcome: null,
    outcomeName: null,
    titleEn: "Multiple Tab Switches Detected",
    titleAr: "تم اكتشاف تبديل متعدد للتبويبات",
    summaryEn:
      "Candidate switched tabs 12 times during the exam, triggering high risk alert",
    summaryAr:
      "قام المرشح بتبديل التبويبات 12 مرة أثناء الاختبار مما أدى إلى تنبيه عالي المخاطر",
    assignedToId: null,
    assignedToName: null,
    createdDate: "2024-02-01T09:30:00Z",
    resolvedDate: null,
  },
];

// Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: 1,
    actorId: "1",
    actorName: "Admin User",
    actorType: "User",
    action: "Exam.Created",
    entityName: "Exam",
    entityId: "1",
    correlationId: "corr-001",
    tenantId: null,
    source: "Web",
    channel: "Admin Portal",
    outcome: "Success",
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0...",
    timestamp: "2024-01-01T10:00:00Z",
    details: '{"examTitle": "Final Mathematics Exam"}',
  },
  {
    id: 2,
    actorId: "3",
    actorName: "Ahmed Hassan",
    actorType: "User",
    action: "Attempt.Started",
    entityName: "Attempt",
    entityId: "1",
    correlationId: "corr-002",
    tenantId: null,
    source: "Web",
    channel: "Candidate Portal",
    outcome: "Success",
    ipAddress: "192.168.1.50",
    userAgent: "Mozilla/5.0...",
    timestamp: "2024-02-01T09:05:00Z",
    details: '{"examId": 1}',
  },
];

// Dashboard Stats
export interface DashboardStats {
  totalExams: number;
  activeExams: number;
  totalAttempts: number;
  passRate: number;
  pendingGrading: number;
  openIncidents: number;
  attemptsOverTime: { date: string; count: number }[];
  riskDistribution: { level: string; count: number }[];
  passRateByExam: { examTitle: string; passRate: number }[];
}

export const mockDashboardStats: DashboardStats = {
  totalExams: 12,
  activeExams: 5,
  totalAttempts: 156,
  passRate: 72.5,
  pendingGrading: 8,
  openIncidents: 3,
  attemptsOverTime: [
    { date: "Jan 1", count: 12 },
    { date: "Jan 8", count: 18 },
    { date: "Jan 15", count: 25 },
    { date: "Jan 22", count: 22 },
    { date: "Jan 29", count: 30 },
    { date: "Feb 5", count: 28 },
    { date: "Feb 12", count: 21 },
  ],
  riskDistribution: [
    { level: "Low", count: 85 },
    { level: "Medium", count: 45 },
    { level: "High", count: 20 },
    { level: "Critical", count: 6 },
  ],
  passRateByExam: [
    { examTitle: "Mathematics", passRate: 78 },
    { examTitle: "Science", passRate: 65 },
    { examTitle: "English", passRate: 82 },
    { examTitle: "History", passRate: 71 },
    { examTitle: "Computer Science", passRate: 69 },
  ],
};
